"""
sequencer.py - Multi-Day Follow-Up Sequencer
=============================================
Module 8 of the AI Lead Generation & Outreach System.

Walks through all prospects with status 'in_sequence', checks whether
each one is due for their next follow-up step based on how many days
have passed since their last contact, generates the right message, and
either prints a preview (dry_run=True) or sends it via mailer.py and
updates the database.

Sequence schedule (configurable at the top of this file):
    Step 1 — Day  0  Initial outreach          (generated by outreach.py)
    Step 2 — Day  3  First follow-up           (short, friendly nudge)
    Step 3 — Day  7  Second follow-up          (add value / offer to close)

After step 3, the prospect's status is moved to 'contacted' and they
exit the sequence.

Usage:
    from sequencer import run_sequence

    # Preview only — nothing is sent, nothing is written to the DB
    run_sequence(dry_run=True)

    # Live — sends emails and updates the database
    run_sequence(dry_run=False)
"""

from datetime import date, timedelta

from deliverability import deliver_prospect_email
from database import (
    DB_PATH,
    get_prospects_in_sequence,
    get_client,
    log_communication_event,
    save_outreach,
    update_outreach_status,
    update_sequence_progress,
    update_status,
)
from outreach import OPT_OUT_LINE, generate_email
from settings import get_sender_name

# ---------------------------------------------------------------------------
# Sequence configuration
# ---------------------------------------------------------------------------

# Each entry defines one step.
#   step  : step number (stored in prospect.sequence_step after sending)
#   day   : minimum days since last_contacted_date before this step is due
#   label : human-readable label for logging
#
# Step 1 has day=0 so a prospect enrolled today is due immediately.
SEQUENCE = [
    {"step": 1, "day": 0, "label": "Initial outreach"},
    {"step": 2, "day": 3, "label": "Follow-up 1 (day 3)"},
    {"step": 3, "day": 7, "label": "Follow-up 2 (day 7)"},
]

# Number of days to wait after the final step before marking as contacted
SEQUENCE_COMPLETE_STATUS = "contacted"


# ---------------------------------------------------------------------------
# Message builders
# ---------------------------------------------------------------------------

def _build_message(prospect: dict, step: int) -> dict:
    """
    Return {"subject": ..., "body": ...} for the given sequence step.

    Step 1 delegates to outreach.generate_email for a fully personalised
    cold email. Steps 2 and 3 are shorter follow-up templates.
    """
    first   = prospect.get("name", "there").split()[0]
    company = prospect.get("company", "your company")

    if step == 1:
        return generate_email(prospect)

    if step == 2:
        subject = f"Re: Quick idea for {company}"
        body = (
            f"Hi {first},\n\n"
            f"Just wanted to bump this up in case it got buried.\n\n"
            f"Would a quick 15-minute call this week make sense?\n\n"
            f"{OPT_OUT_LINE}\n\n"
            f"Best,\n"
            f"{get_sender_name()}"
        )
        return {"subject": subject, "body": body}

    # step == 3
    subject = f"Last note — {company}"
    body = (
        f"Hi {first},\n\n"
        f"I'll keep this short — I don't want to clog your inbox.\n\n"
        f"If building a more predictable outbound pipeline is a priority "
        f"for {company} right now, I'd love to show you what we're doing "
        f"for similar teams. If the timing isn't right, no worries at all.\n\n"
        f"{OPT_OUT_LINE}\n\n"
        f"Either way, thanks for your time.\n\n"
        f"Best,\n"
        f"{get_sender_name()}"
    )
    return {"subject": subject, "body": body}


# ---------------------------------------------------------------------------
# Due-date logic
# ---------------------------------------------------------------------------

def _next_step(prospect: dict) -> dict | None:
    """
    Return the next SEQUENCE entry this prospect is due for, or None.

    A prospect is due for step N when:
      - Their current sequence_step is N-1  (they haven't done step N yet)
      - AND the required number of days has passed since last_contacted_date
        (or last_contacted_date is None, meaning they just enrolled)
    """
    current_step = prospect.get("sequence_step") or 0
    last_date_str = prospect.get("last_contacted_date")

    last_date = (
        date.fromisoformat(last_date_str) if last_date_str else date.min
    )
    today = date.today()

    for entry in SEQUENCE:
        if entry["step"] == current_step + 1:
            due_on = last_date + timedelta(days=entry["day"])
            if today >= due_on:
                return entry
            break  # found the right step but not due yet

    return None  # all steps done, or not due yet


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_due_prospects(db_path: str = DB_PATH) -> list:
    """
    Return prospects that are in the sequence and due for their next step.

    Each returned dict is the prospect record augmented with a
    'next_step' key holding the matching SEQUENCE entry.

    Args:
        db_path: Path to the database file.

    Returns:
        List of prospect dicts with a 'next_step' key added.
    """
    due = []
    for prospect in get_prospects_in_sequence(db_path):
        step_entry = _next_step(prospect)
        if step_entry:
            due.append({**prospect, "next_step": step_entry})
    return due


def run_sequence(dry_run: bool = True, db_path: str = DB_PATH) -> list:
    """
    Process all prospects due for their next sequence step.

    Args:
        dry_run: If True (default), prints what would be sent but does NOT
                 call mailer.py or update the database. Safe to run any time.
                 If False, sends emails via mailer.send_email() and writes
                 progress back to the database.
        db_path: Path to the database file.

    Returns:
        A list of result dicts, one per prospect processed:
            prospect_id   - int
            name          - str
            step          - int  (the step that was/would be sent)
            label         - str  (human-readable step name)
            subject       - str
            sent          - bool (False in dry_run mode)
            error         - str  (empty string on success)
    """
    mode_label = "[DRY RUN]" if dry_run else "[LIVE]"
    sep  = "=" * 64
    dash = "-" * 64

    print(f"\n{sep}")
    print(f"  SEQUENCER  {mode_label}")
    print(sep)

    due = get_due_prospects(db_path)

    if not due:
        print("\n  No prospects are due for a sequence step today.\n")
        return []

    print(f"\n  {len(due)} prospect(s) due for follow-up:\n")

    results = []
    today_str = date.today().isoformat()

    for prospect in due:
        step_entry = prospect["next_step"]
        step       = step_entry["step"]
        label      = step_entry["label"]
        message    = _build_message(prospect, step)
        subject    = message["subject"]
        body       = message["body"]
        email      = prospect.get("email", "")

        print(f"  {dash}")
        print(f"  Prospect : {prospect['name']} at {prospect['company']}")
        print(f"  Email    : {email or '(no email on file)'}")
        print(f"  Step     : {step} — {label}")
        print(f"  Subject  : {subject}")
        print(f"  Body preview:\n")
        for line in body.splitlines()[:4]:
            print(f"    {line}")
        if body.count("\n") >= 4:
            print("    ...")

        sent  = False
        error = ""

        if dry_run:
            print(f"\n  {mode_label} Would send to {email} — no action taken.")
        elif not email:
            error = "No email address on file — skipped."
            log_communication_event(
                prospect["id"], "email", "outbound", "sequence_step", "skipped",
                content_excerpt=subject, metadata=error, db_path=db_path
            )
            print(f"\n  SKIPPED: {error}")
        else:
            # Check if the client has outreach review mode on
            _cid = prospect.get("client_id", 1)
            _client = get_client(_cid, db_path=db_path)
            _review_mode = bool((_client or {}).get("outreach_review_mode"))

            if _review_mode:
                # Hold for client review instead of sending
                outreach_id = save_outreach(
                    prospect_id=prospect["id"],
                    subject=subject,
                    body=body,
                    client_id=_cid,
                    db_path=db_path,
                )
                update_outreach_status(outreach_id, "pending_review", db_path=db_path)
                log_communication_event(
                    prospect["id"], "email", "outbound", "sequence_step", "pending_review",
                    content_excerpt=subject,
                    metadata=f"step={step};label={label};outreach_id={outreach_id};review_mode=1",
                    db_path=db_path,
                )
                print(f"\n  QUEUED FOR REVIEW (outreach_id={outreach_id}).")
            else:
                delivery = deliver_prospect_email(
                    to_address=email,
                    subject=subject,
                    body=body,
                    prospect_id=prospect["id"],
                    event_type="sequence_step",
                    client_id=_cid,
                    db_path=db_path,
                    content_excerpt=subject,
                    metadata=f"step={step};label={label}",
                )
                sent = delivery["sent"]
                error = delivery["error"]
                if sent:
                    update_sequence_progress(prospect["id"], step, today_str, db_path)
                    # After the final step, move the prospect out of the sequence
                    if step == SEQUENCE[-1]["step"]:
                        update_status(prospect["id"], SEQUENCE_COMPLETE_STATUS, db_path)
                        print(f"\n  Sent. Sequence complete — status set to '{SEQUENCE_COMPLETE_STATUS}'.")
                    else:
                        print(f"\n  Sent. Next step due in {SEQUENCE[step]['day']} day(s).")
                else:
                    print(f"\n  FAILED: {error}")

        results.append({
            "prospect_id": prospect["id"],
            "name":        prospect["name"],
            "step":        step,
            "label":       label,
            "subject":     subject,
            "sent":        sent,
            "error":       error,
        })

    print(f"\n{sep}\n")
    return results
